# Generated by Django 6.0.4 on 2026-05-07 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('vehicule', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='livreurs/')),
                ('is_online', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('hors_ligne', 'Hors-ligne')], default='hors_ligne', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('en_route', 'En route'), ('collecte', 'Colis récupéré'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proof_of_delivery', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('signature', models.TextField(blank=True, null=True)),
                ('qr_code_verified', models.BooleanField(default=False)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='reservations.reservation')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='delivery.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='delivery.livraison')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='delivery.livreur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='delivery.livraison')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
