# Generated by Django 6.0.4 on 2026-05-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_medecin_latitude_medecin_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pack_type',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('senior', 'Senior')], default='junior', max_length=10, null=True),
        ),
    ]
