# Generated by Django 6.0.4 on 2026-05-06 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin_name', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(max_length=100)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('status', models.CharField(default='attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_as_medecin', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
