# Generated by Django 6.0.4 on 2026-05-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
