# Generated by Django 6.0.4 on 2026-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_ordonnance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='address',
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_proche',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
