# Generated by Django 6.0.4 on 2026-05-08 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_address_and_more'),
        ('users', '0003_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances_emises', to='users.medecin'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_as_medecin', to='users.medecin'),
        ),
    ]
