# Generated by Django 6.0.4 on 2026-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_ordonnance_medecin_alter_reservation_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='EN_ATTENTE', max_length=50),
        ),
    ]
