# Generated by Django 6.0.4 on 2026-05-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_delivery_lat_reservation_delivery_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnance_doc', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='status',
            field=models.CharField(default='ORDONNANCE_DISPONIBLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
